### ISSUE TITLE
소셜 유저가 동일 상품 중복 구매 후 리뷰 생성 시 오류 수정

### ISSUE THREAD

**Issue by mingdorri** [cwc-moamoa/moamoa#52]
## 어떤 기능인가요?
> 소셜 유저가 동일 상품을 두 번 이상 구매시
리뷰 작성을 할 때 상품 구매 내역이 두 개가 있으므로
유니크한 값이 되어 오류가 발생함

## 작업 상세 내용
- [ ] 소셜 유저가 동일 상품 중복 구매 후 리뷰 생성 시 오류 수정

**Comment by Karox1234** [comment]
다른 분에게 이슈 이전
